Logo:
  default: "https://enertime.sharewoods.io/uploads/default/original/1X/23cf96716c72e567a54d944c5376089ae6efe1b3.svg"
  description:
    en: "Enter the URL of the logo you wish to use."
    fr: "Entrez l'URL du logo de la société"
Heading:
  default: "This is a header"
  max: 25
  description:
    en: "Text for the heading in the footer - you can use your site name for example - Max length 25 characters"
Description:
  default: "Descriptive text..."
  max: 180
  description:
    en: "Enter a short description about your community - Max length 180 characters"
Small_links:
  type: list
  list_type: simple
  default: "Privacy, #, self|Terms of service, #, self| About, #, self"
  description:
    en: "You can add small links at the bottom of the footer like Terms of Service and Privacy. One item per line in this order:<br>Text, URL, target<br><b>Text:</b> The text that shows for the small link<br><b>URL:</b> The path of the link<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab"
Social_links:
  type: list
  list_type: simple
  default: "LinkedIn, Follow us on LinkedIn, #, blank, fab-linkedin|Facebook, Follow us on Facebook, #, blank,fab-facebook|Twitter, Follow us on Twitter, #, blank,fab-twitter| Youtube, Follow us on Youtube, #, blank,fab-youtube"
  description:
    en: "Enter the social links you'd like to add to the footer in this format:<br> provider, title, URL, target<br><b>Provider:</b> is the name of the provider like Facebook or Twitter<br><b>Title:</b> The text that shows when the link is hovered<br><b>URL:</b> The path you'd like the link to have<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab<br><b>Icon:</b> use a FontAwesome5 icon name (brand icons need a 'fab-' prefix)."
Show_footer_on_login_required_page:
  default: true
  description:
    en: "Check this setting if you want the footer to be displayed on the login-required page (only applies if your site is private)"
svg_icons:
  default: "fab-linkedin|fab-facebook|fab-twitter|fab-youtube"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in the social links setting above. "
